### ISSUE TITLE
Adding a Video Gallery section for pictures 

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/voyager-hf#6]
<h2 align="center">Issue picture</h2>
<div align="center">
<p> Adding a Video gallery below the about me page as a separate div for eg: </p>
<img src="https://cdn.discordapp.com/attachments/740981051098398751/878193803662622720/unknown.png">
<p>You may use the following links for your reference:</p>
<p><a href="https://codemyui.com/pixelated-movement-effect-for-images-with-hover-dissolve-animation-using-gsap/">
https://codemyui.com/pixelated-movement-effect-for-images-with-hover-dissolve-animation-using-gsap/ </a>
<a href="https://codemyui.com/bay-window-style-image-slider-with-scroll-effect/"> https://codemyui.com/bay-window-style-image-slider-with-scroll-effect/ </a> </p><br>
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>
</div>

**Comment by nverbois** [comment]
Hi, 

I'm interested in working on this issue. 

Let me know if I can try to solve it ;)

**Comment by pulkithanda** [comment]
Hey there! Sure go ahead, Assigned the issue to you. Good luck.
(btw if you could star it and follow me it would be great :) thanks)

**Comment by nverbois** [comment]
Hi, 

I've used the second reference that you have suggested above, and tweaked it to intagrate Youtube videos thumbnails in the gallery.
This has been pushed on my branch, and I would gladly receive your feedback on that.
Let me know if you want any changes or improvments.

Thank you in advance.

**Comment by pulkithanda** [comment]
Hey, @nverbois Your image gallery is just perfect! though id, like to add a few things first just increasing the height of the div container which holds the video gallery by 1 to 2 cm, make it a little high so that side frames are included. The second thing is that the user may not know that it is a bay window effect you can drag it so just create two buttons which indicate scroll left and right like you have mouse pointers saying scroll down something like that so that you as a general user would know it. The third is responsiveness if you could just make it a little more responsive (optional) that's it, ill merge it then thanks a lot mate!

**Comment by nverbois** [comment]
Hi @pulkithanda , 

Thank you for your feedback and suggestions ! I'm glad to hear that the video gallery suits you, and I'll be working on those small remaining issues as soon as possible.

**Comment by nverbois** [comment]
Hello @pulkithanda,

I've worked on your first two comments, concerning the height of the div container which holds the video gallery as well as changing the aspect of the mouse cursor when people scroll the gallery. 
The changes I've made have been pushed to my branch, I hope you'll like it! 

Concerning the responsiveness, unfortunately, I had a bit of a hard time finding how to make it properly responsive, and I think I might leave this aside since you mentioned it was optional. 

Also, let me know if I can send the pull request ;)

**Comment by pulkithanda** [comment]
Hey there @nverbois Just if you think adding a video gallery heading if it seems suitable doesn't spoil the effects of the bay window gallery effect and a suitable background colour this is fine too. Done nothing else to do, Just send your PR ill accept it. You've done great work. (btw if it helped you, please consider following me, and starring the repository, helps me as a maintainer and would help me in further projects too, thanks!)

**Comment by nverbois** [comment]
Hey @pulkithanda ,

Thank you for your final feedback on my contribution. 
I've added a heading to the video gallery using the same text formatting as you used above on the home page. Regarding the background color, I was at first using the same shade of "black/grey" as you used for the navigation bar, but I have changed it to white now, as I find it to be more suitable for the whole homepage design. 

I will thus send my Pull Request soon, in order to fetch upstream and review changes or resolve conflicts. 

PS : I clicked the follow button on your page and have starred the repository. I will also have a look at your other and future projects in order to support you ;)
